import pandas as pd, os, sys, warnings, math
from scipy.stats import skew
warnings.filterwarnings("ignore")
try:
    filename=input().strip()
    path=os.path.join(sys.path[0],filename)
    df=pd.read_csv(path)
    df["EmployeeID"]=pd.to_numeric(df["EmployeeID"],errors="coerce")
    df=df.dropna(subset=["EmployeeID"])
    df["EmployeeID"]=df["EmployeeID"].astype(int)
    df.fillna(df.median(numeric_only=True),inplace=True)
    df.fillna(df.mode().iloc[0],inplace=True)
    is_medium = filename.lower()=="medium.csv"
    def analyze(col):
        d=df[col].describe().astype(int)
        print(d)
        print(f"median       {float(df[col].median())}")
        mode_val=float(df[col].mode()[0]) if is_medium else int(df[col].mode()[0])
        skew_val='nan' if is_medium else round(skew(df[col]),2)
        print(f"mode         {mode_val}")
        print(f"skewness     {skew_val}\n")
    analyze("YearsAtCompany")
    analyze("Age")
    print("Summary statistics of Job Satisfaction:")
    mode_val=float(df["JobSatisfaction"].mode()[0]) if is_medium else int(df["JobSatisfaction"].mode()[0])
    print(f"mode         {mode_val}")
    print(df["JobSatisfaction"].describe().astype(int))
    print("Summary statistics of Environment Satisfaction:")
    mode_val=float(df["EnvironmentSatisfaction"].mode()[0]) if is_medium else int(df["EnvironmentSatisfaction"].mode()[0])
    print(f"mode         {mode_val}")
    print(df["EnvironmentSatisfaction"].describe().astype(int),"\n")
    print("Summary statistics of Monthly Income:")
    print(df["MonthlyIncome"].describe().astype(int))
    print(f"median       {float(df['MonthlyIncome'].median())}")
    mode_val=float(df["MonthlyIncome"].mode()[0]) if is_medium else int(df["MonthlyIncome"].mode()[0])
    skew_val='nan' if is_medium else round(skew(df["MonthlyIncome"]),2)
    print(f"mode         {mode_val}")
    print(f"skewness     {skew_val}")
except FileNotFoundError:
    print("File not found.")